INSERT INTO random_comments VALUES ('The meetup was great, but it was quite too pricey for me');
INSERT INTO random_comments VALUES ('The event was super fun! Hope to go for it again in the near future!');
INSERT INTO random_comments VALUES ('Love it! The host was super fun and chill');
INSERT INTO random_comments VALUES ('Everybody had fun in the event');
INSERT INTO random_comments VALUES ('The event started on time and it was great');
INSERT INTO random_comments VALUES ('It was very exciting to do something new');
INSERT INTO random_comments VALUES ('Good experience and amazing company');
INSERT INTO random_comments VALUES ('Definitely will go for it again');
INSERT INTO random_comments VALUES ('It super exhausting, but it was great to meet new people');
INSERT INTO random_comments VALUES ('Love it! Made some good friends from the meetup');
INSERT INTO random_comments VALUES ('Had a blast that that night, cant wait to go for it again!');
INSERT INTO random_comments VALUES ('There was a lot of good vibes! I had a really great time in the meetup. ');
INSERT INTO random_comments VALUES ('What a great time to disconnect to connect. Would not have been possible without the amazing people I met!');
INSERT INTO random_comments VALUES ('Didnt expect much from the hangout but it definitely exceeded my expectations.');
INSERT INTO random_comments VALUES ('Super fun and enjoyable');
INSERT INTO random_comments VALUES ('It was a great time to chill and relax from work');
INSERT INTO random_comments VALUES ('Cannot remember when was the last time I had as much fun as that night!');
INSERT INTO random_comments VALUES ('Made great memories and friends from the hangout!');
INSERT INTO random_comments VALUES ('It was my first time trying and turns out it is not that bad');
INSERT INTO random_comments VALUES ('Had a fun and chill time with everyone'); 